apiVersion: v1
kind: Service
metadata:
  name: backend-article
spec:
  selector:
    app: article-pod
    tier: backend-article
  ports:
  - protocol: TCP
    port: 6003
    targetPort: 6003
  type: LoadBalancer