apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-repa
spec:
  progressDeadlineSeconds: 240
  selector:
    matchLabels:
      app: repa-pod
      tier: backend-repa
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: repa-pod
        tier: backend-repa
        track: stable
    spec:
      volumes:
        - name: repa-volume
          persistentVolumeClaim:
            claimName: repa-persistent-volume-claim

      containers:
        - name: repa-container
          image: grigorytitov/docker-freeai-repa-image:v1
          imagePullPolicy: Always
          #command: ["npm","test"] #Для запуска тестов
          ports:
            - name: http
              containerPort: 6003
          env:
            - name: DB_USER
              value: postgres
            - name: DB_HOST
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "db_repas"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD

            - name: KAFKA_CLIENT_ID
              value: "repa-app"
            - name: KAFKA_BROCKERS_HOST
              value: kafka
            - name: KAFKA_BROCKERS_PORT
              value: "29092"
            - name: KAFKA_BROCKERS_REPLICATION_FACTOR
              value: "2"

            - name: REDIS_NAME
              value: ""
            - name: REDIS_PASSWORD
              value: ""
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_DB
              value: "0"
          volumeMounts:
            - mountPath: /public
              name: repa-volume