apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      component: frontend
  template:
    metadata:
      labels:
        component: frontend
    spec:
      containers:
        - name: frontend-container
          image: grigorytitov/docker-siencehub-frontend-image:v1
          #imagePullPolicy: Always #Для подгрузки обновлений с DockerHub
          ports:
            - containerPort: 3000