apiVersion: v1
kind: Service
metadata:
  name: backend-product
spec:
  selector:
    app: product-pod
    tier: backend-product
  ports:
  - protocol: TCP
    port: 6010
    targetPort: 6010
  type: LoadBalancer