apiVersion: batch/v1
kind: Job
metadata:
  name: pg-job-create-db
spec:
  template:
    spec:
      containers:
      - name: postgres-job-container
        image: postgres
        env:
        - name: PGHOST
          value: postgres
        - name: PGUSER
          value: postgres
        - name: PGPASSWORD
          valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD
        - name: PGDATABASE
          value: "postgres"
        command: 
            - /bin/sh
            - -c
            - |
              psql -c "CREATE DATABASE db_users;"
              psql -c "CREATE DATABASE db_repas;"
              psql -c "CREATE DATABASE db_relationships;"
              psql -c "CREATE DATABASE db_logs;"
              psql -c "CREATE DATABASE db_chats;"
              psql -c "CREATE DATABASE db_baskets;"
      restartPolicy: Never
  backoffLimit: 4